---
title: "Refrence_content"
author: "Jonathan"
date: "June 5, 2018"
output: html_document
---

# PRoc contents from SAS where exported to CSV  in order to be used as  interactive guide in Shinny

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

packs<-c("dplyr","magrittr","readr","ggplot2")
lapply(packs,require, character.only = TRUE)



#library(dplyr)
#library(readr)
#library(shiny)
#library(tidyr)
library(sas7bdat)

setwd("E:\\Users\\josanchez\\References")

read_cont <- function(read = "TED.csv") {
  x <- read_csv(read)  
  x %<>% select(NAME,LABEL,FORMAT)
  return(x)
}

#read Files
list.files(pattern = "csv")

TED <- read_cont( read = "E:\\Users\\josanchez\\References\\TED.CSV")
CRF_allo <- read_cont(read = "E:\\Users\\josanchez\\References\\CRF_allo.csv")
CRF_auto <- read_cont(read = "E:\\Users\\josanchez\\References\\CRF_auto.csv")
#Lk1801_cont <- read_cont("E:\\Users\\josanchez\\References\\LK1801_content.csv")
LK1801 <- read.sas7bdat('E:/Users/josanchez/WC_datastes/LK-1801/SAS_programs/Sub_programs/final.sas7bdat')

x<- c("disrelhi", "cldzashi", 'frelpshi', 'fsrlbrhi', 'cyrlbrhi', 'relprghi', 'clnrelhig', 'cytrelhig', 'molrelhig', 'amstathi')
x[x%in% TED$NAME]


names <-as.data.frame(names(LK1801))

```
##names Check for specific cytogenetics 
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
#function for txt search in the variables
cytosearch <- function(x= CRF,pattern= "f3id")
{
  x <- x[agrepl(pattern,x$NAME),]
  return(x)
}

#create txt matching vectors
F3_ted <-  cytosearch(x= TED, pattern = "f3id") %>% mutate(source = "TED")
F3_CRF <- cytosearch(x= CRF, pattern = "f3id") %>% mutate(source = 'CRF')

F3 <- F3_CRF %>% filter(NAME %in% (F3_ted$NAME))

#NPM1
npm1_ted <-  cytosearch(x= TED, pattern = "npm1") %>% mutate(source = 'TED')
npm1_CRF <- cytosearch(x= CRF, pattern = "npm1") %>% mutate(source = 'CRF')

NPM1 <- npm1_CRF %>% filter(NAME %in% (npm1_ted$NAME))
#cebpa 
cebpa_ted <-  cytosearch(x= TED, pattern = "cebpa") %>% mutate(source = 'TED')
cebpa_CRF <- cytosearch(x= CRF, pattern = "cebpa") %>% mutate(source = 'CRF')
cebpa <- cebpa_CRF %>% filter(NAME %in% (cebpa_ted$NAME)) 

#create a stak table to select variables
combined_cyto <- bind_rows(F3,NPM1,cebpa)

#combined at DX and PR
DX_PR<- combined_cyto[agrepl(combined_cyto$LABEL,pattern = "Diagnosis",fixed = T) | agrepl(combined_cyto$LABEL,pattern = "Between",fixed = T), ]

#write_csv(DX_PR,"LK1801_DXPR.csv")

#write_csv(combined_cyto,"cyto_vars_lk1801.csv")


vars <- combined_cyto$NAME

#check For other molecular Markers  (OMOL) omoldxsp found V3  of the CRF

```

#read CaChes CSV file 
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
cache <- read_csv('LK18-01.csv')
levels(as.factor(cache$omoldxsp))

#Create  funtion to check variables in the chatacter form

other_cyto <- function(x= omoldxsp,pattern = "RUNX") {
z <- x[agrepl(pattern,x,ignore.case = T)]
return(z)
}

```



# Sting in other Cytogenetics 

#RUNX mutation
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
other_cyto(x=cache$omoldxsp, pattern = "RUNX")
other_cyto(x=cache$omolprsp, pattern = "RUNX")
#other_cyto(x=cache$othendpr, pattern = "RUNX")
#other_cyto(x=cache$othexdx, pattern = "RUNX")

#table(cache$runx1pr)
```

##ASXL1
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
other_cyto(x=cache$omoldxsp, pattern = "ASXL")
other_cyto(x=cache$omolprsp, pattern = "ASXL")
#other_cyto(x=cache$othendpr, pattern = "ASXL")
#other_cyto(x=cache$othexdx, pattern = "ASXL")
#table(cache$asxl1dx)
```

##CEBPA
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
other_cyto(x=cache$omoldxsp, pattern = "CEBPA")
other_cyto(x=cache$omolprsp, pattern = "CEBPA")
#other_cyto(x=cache$othendpr, pattern = "CEBPA")
#other_cyto(x=cache$othexdx, pattern = "CEBPA")

```



##"npm1"
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
other_cyto(x=cache$omoldxsp, pattern = "npm1")
other_cyto(x=cache$omolprsp, pattern = "npm1")
#other_cyto(x=cache$othendpr, pattern = "npm1")
#other_cyto(x=cache$othexdx, pattern = "npm1")
```

##"f3id"
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
other_cyto(x=cache$omoldxsp, pattern = "FLT3")
other_cyto(x=cache$omolprsp, pattern = "FLT3")
#other_cyto(x=cache$othendpr, pattern = "FLT3")
#other_cyto(x=cache$othexdx, pattern = "FLT3")
```

```{r}
# '/RUNX1|ASXL1/i'
#cache$omoldxsp[grepl('/RUNX1|ASXL1/i',cache$omoldxsp,perl= TRUE)]

#grepl('/RUNX1|ASXL1/i',cache$omoldxsp,perl= TRUE)



TED$NAME[grepl("reldtf",TED$NAME)]



```
#MRD Clasification 
```{r}
var_mrd <- c('kpspr','graftype','wtpr','htpr','bumeth','rcmvpr','dcmvpr','donorm','donorf', 'myeloabl', 'condclas',  'prelk' ,'leuk2', 'molrempr','flwcytcr','cytrempr')

length(var_mrd)

length(var_mrd %in%  names(LK1801))

```
#All relapse var  from TED and CRF

```{r}
relapse_ted<- TED$NAME[grepl("relapse",TED$LABEL,perl =T,ignore.case = T)]


relapse_crf <- CRF$NAME[grepl("relapse",CRF$LABEL,perl =T,ignore.case = T)]

```





